/** Countries offered when a borrower declares foreign citizenship. */
export interface CountryOption {
  value: string; // ISO 3166-1 alpha-2
  label: string; // Hebrew name
}

export const COUNTRIES: CountryOption[] = [
  { value: 'US', label: 'ארצות הברית' },
  { value: 'RU', label: 'רוסיה' },
  { value: 'UA', label: 'אוקראינה' },
  { value: 'FR', label: 'צרפת' },
  { value: 'GB', label: 'בריטניה' },
  { value: 'CA', label: 'קנדה' },
  { value: 'DE', label: 'גרמניה' },
  { value: 'AR', label: 'ארגנטינה' },
  { value: 'BR', label: 'ברזיל' },
  { value: 'AU', label: 'אוסטרליה' },
  { value: 'ZA', label: 'דרום אפריקה' },
  { value: 'ET', label: 'אתיופיה' },
  { value: 'MA', label: 'מרוקו' },
  { value: 'BE', label: 'בלגיה' },
  { value: 'NL', label: 'הולנד' },
  { value: 'CH', label: 'שווייץ' },
  { value: 'IT', label: 'איטליה' },
  { value: 'ES', label: 'ספרד' },
  { value: 'PT', label: 'פורטוגל' },
  { value: 'PL', label: 'פולין' },
  { value: 'HU', label: 'הונגריה' },
  { value: 'RO', label: 'רומניה' },
  { value: 'BG', label: 'בולגריה' },
  { value: 'CZ', label: "צ'כיה" },
  { value: 'AT', label: 'אוסטריה' },
  { value: 'SE', label: 'שוודיה' },
  { value: 'NO', label: 'נורווגיה' },
  { value: 'DK', label: 'דנמרק' },
  { value: 'FI', label: 'פינלנד' },
  { value: 'IE', label: 'אירלנד' },
  { value: 'GR', label: 'יוון' },
  { value: 'TR', label: 'טורקיה' },
  { value: 'GE', label: 'גאורגיה' },
  { value: 'AZ', label: 'אזרבייג׳ן' },
  { value: 'UZ', label: 'אוזבקיסטן' },
  { value: 'KZ', label: 'קזחסטן' },
  { value: 'BY', label: 'בלארוס' },
  { value: 'MD', label: 'מולדובה' },
  { value: 'LV', label: 'לטביה' },
  { value: 'LT', label: 'ליטא' },
  { value: 'EE', label: 'אסטוניה' },
  { value: 'MX', label: 'מקסיקו' },
  { value: 'CL', label: "צ'ילה" },
  { value: 'CO', label: 'קולומביה' },
  { value: 'PE', label: 'פרו' },
  { value: 'UY', label: 'אורוגוואי' },
  { value: 'VE', label: 'ונצואלה' },
  { value: 'IN', label: 'הודו' },
  { value: 'CN', label: 'סין' },
  { value: 'JP', label: 'יפן' },
  { value: 'KR', label: 'דרום קוריאה' },
  { value: 'PH', label: 'הפיליפינים' },
  { value: 'TH', label: 'תאילנד' },
  { value: 'NZ', label: 'ניו זילנד' },
  { value: 'IR', label: 'איראן' },
  { value: 'IQ', label: 'עיראק' },
  { value: 'EG', label: 'מצרים' },
  { value: 'JO', label: 'ירדן' },
  { value: 'TN', label: 'תוניסיה' },
  { value: 'DZ', label: "אלג'יריה" },
  { value: 'LY', label: 'לוב' },
  { value: 'YE', label: 'תימן' },
  { value: 'OTHER', label: 'אחר' },
];

export function countryLabel(code: string | null | undefined): string {
  if (!code) return '—';
  return COUNTRIES.find((c) => c.value === code)?.label ?? code;
}
