import type { DemoFlow } from '../../types';

/** הדגמת ניהול המסמכים ותהליך העבודה — תיק המסמכים, ההעלאה, המשימות והשלבים */
const flow: DemoFlow = {
  id: 'documents',
  title: 'ניהול מסמכים ותהליך העבודה',
  description: 'איך הניירת זורמת בתהליך',
  route: '/demo/plan',
  exitRoute: '/',
  initialState: { docTitle: 'תדפיס עו״ש 3 חודשים' },
  nextDemos: ['plan-stages', 'client-dashboard', 'client-area'],
  steps: [
    {
      id: 'intro',
      title: 'הניירת של המשכנתא',
      caption: 'הבנק לא מסתמך על הצהרות — הוא מאמת מול מסמכים. משכלנתא יודעת אילו מסמכים יידרשו לפי הרכב הלווים ואופן ההעסקה, ועוקבת אחרי מה שנאסף.',
      target: 'plan-header',
      spotlight: { side: 'bottom' },
      duration: 6000,
    },
    {
      id: 'vault-button',
      title: 'תיק המסמכים',
      caption: 'הכפתור זמין מכל שלב, ופס ההתקדמות שמתחתיו מראה כמה מהמסמכים הנדרשים כבר בתיק.',
      target: 'vault-button',
      spotlight: { side: 'bottom' },
    },
    {
      id: 'vault-open',
      title: 'התקדמות לפי שלב',
      caption: 'נפתח את התיק. למעלה ההתקדמות לכל שלב ולכל התהליך; מתחת — כל המסמכים שהועלו, עם צפייה ומחיקה. האישורים העקרוניים משלושה בנקים כבר כאן.',
      actions: [{ type: 'click', target: 'vault-button' }],
      target: 'vault-list',
      spotlight: { side: 'top' },
      duration: 6500,
    },
    {
      id: 'upload',
      title: 'העלאה בכותרת חופשית',
      caption: 'מסמך שלא ברשימה? מעלים אותו בכותרת חופשית — הכותרת היא המפתח שבו הוא יישמר ויישויך לשלב הנוכחי. נכתוב: {{docTitle}}.',
      actions: [
        { type: 'click', target: 'vault-upload-free' },
        { type: 'type', target: 'upload-title', value: 'תדפיס עו״ש 3 חודשים', key: 'docTitle' },
      ],
      target: 'upload-file',
      spotlight: { side: 'top' },
      allowTryIt: true,
      tryItHint: 'בחרו קובץ מהמחשב ולחצו "העלאה לתיק" — בהדגמה הקובץ נשאר בדפדפן ואינו נשלח לשום מקום.',
    },
    {
      id: 'upload-explain',
      title: 'הקובץ',
      caption: 'כאן בוחרים PDF או תמונה. בתהליך אמיתי הקובץ נשמר באחסון פרטי ומוצג רק לכם וליועץ. בהדגמה נדלג על בחירת הקובץ.',
      target: 'upload-file',
      spotlight: { side: 'top' },
    },
    {
      id: 'close',
      title: 'המסמכים בשלב',
      caption: 'נסגור את החלונות ונעבור לשלב האישור העקרוני — שם המסמכים פוגשים את הבנקים.',
      actions: [
        { type: 'key', key: 'Escape' },
        { type: 'wait', ms: 400 },
        { type: 'key', key: 'Escape' },
        { type: 'wait', ms: 400 },
        { type: 'click', target: 'plan-stage-APPLICATIONS' },
        { type: 'click', target: 'plan-stage-gate-self', optional: true },
      ],
      target: 'plan-stage-title',
      spotlight: { side: 'bottom' },
    },
    {
      id: 'approvals',
      title: 'אישורים עקרוניים',
      caption: 'בשלב הזה מגישים את המסמכים לכמה בנקים ומקבלים אישור עקרוני מכל אחד — הוא נשמר בתיק כמסמך, והשלב מסמן אילו בנקים כבר אישרו.',
      target: 'plan-stage-content',
      spotlight: { side: 'over' },
      duration: 6500,
    },
    {
      id: 'tasks',
      title: 'משימות השלב',
      caption: 'לכל שלב יש משימות מתוכננות: מה להביא, עד מתי ולאיזה בנק. משימת מסמך נסגרת אוטומטית כשהקובץ עולה לתיק.',
      actions: [{ type: 'click', target: 'plan-stage-ANALYSIS' }, { type: 'scroll', target: 'plan-stage-tasks' }],
      target: 'plan-stage-tasks',
      spotlight: { side: 'top' },
      duration: 6000,
    },
    {
      id: 'advisor',
      title: 'עם היועץ',
      caption: 'היועץ רואה את אותו תיק: מה נאסף, מה חסר, ומה צריך לתקן — ומשאיר הערות בשלב. אתם רואים את ההערות מעל תוכן השלב.',
      target: 'plan-stage-content',
      spotlight: { side: 'over' },
    },
    {
      id: 'end',
      title: 'הניירת זורמת',
      caption: 'תיק אחד, מסמך אחד לכל דרישה, התקדמות ברורה לכל שלב — וכשמגיעים לחתימה, הכול כבר מסודר.',
      target: 'vault-button',
      spotlight: { side: 'bottom' },
      duration: 5000,
    },
  ],
};

export default flow;
